// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CZbor.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Proto {

  /// <summary>Holder for reflection information generated from CZbor.proto</summary>
  public static partial class CZborReflection {

    #region Descriptor
    /// <summary>File descriptor for CZbor.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CZborReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgtDWmJvci5wcm90bxIFcHJvdG8iKQoHQW5nYWphdBIMCgR1c2VyGAEgASgJ",
            "EhAKCHBhc3N3b3JkGAIgASgJIlQKBFpib3ISEgoKZGVzdGluYXRpYRgBIAEo",
            "CRIUCgxkYXRhUGxlY2FyaWkYAiABKAkSEAoIYWVyb3BvcnQYAyABKAkSEAoI",
            "bnJMb2N1cmkYBCABKAUiFgoGVHVyaXN0EgwKBG51bWUYASABKAkirwEKBUJp",
            "bGV0Eh8KB2FuZ2FqYXQYASABKAsyDi5wcm90by5BbmdhamF0EhkKBHpib3IY",
            "AiABKAsyCy5wcm90by5aYm9yEh0KBmNsaWVudBgDIAEoCzINLnByb3RvLlR1",
            "cmlzdBIjCgxsaXN0YVR1cmlzdGkYBCADKAsyDS5wcm90by5UdXJpc3QSFAoM",
            "YWRyZXNhQ2xpZW50GAUgASgJEhAKCG5yTG9jdXJpGAYgASgFIssCCgdSZXF1",
            "ZXN0EigKBHR5cGUYASABKA4yGi5wcm90by5SZXF1ZXN0LlJlcXVlc3RUeXBl",
            "EhsKBHpib3IYAiABKAsyCy5wcm90by5aYm9ySAASDgoEbmFtZRgDIAEoCUgA",
            "Eh0KBWJpbGV0GAQgASgLMgwucHJvdG8uQmlsZXRIABIhCgdhbmdhamF0GAUg",
            "ASgLMg4ucHJvdG8uQW5nYWphdEgAEh8KBnR1cmlzdBgGIAEoCzINLnByb3Rv",
            "LlR1cmlzdEgAIn4KC1JlcXVlc3RUeXBlEgkKBUxPR0lOEAASDwoLR0VUX1pC",
            "T1JVUkkQARISCg5GSUxURVJfWkJPUlVSSRACEg0KCUJVWV9CSUxFVBADEhMK",
            "D0ZJTkRfQUREX1RVUklTVBAEEg8KC1VQREFURV9aQk9SEAUSCgoGTE9HT1VU",
            "EAZCBgoEZGF0YSLWAgoIUmVzcG9uc2USKgoEdHlwZRgBIAEoDjIcLnByb3Rv",
            "LlJlc3BvbnNlLlJlc3BvbnNlVHlwZRINCgVlcnJvchgCIAEoCRIfCgdhbmdh",
            "amF0GAMgASgLMg4ucHJvdG8uQW5nYWphdBIcCgd6Ym9ydXJpGAQgAygLMgsu",
            "cHJvdG8uWmJvchIMCgRudW1lGAUgASgJEh0KBnR1cmlzdBgGIAEoCzINLnBy",
            "b3RvLlR1cmlzdBIZCgR6Ym9yGAcgASgLMgsucHJvdG8uWmJvciKHAQoMUmVz",
            "cG9uc2VUeXBlEgYKAk9LEAASCQoFRVJST1IQARIPCgtHRVRfWkJPUlVSSRAC",
            "EhIKDkZJTFRFUl9aQk9SVVJJEAMSEwoPRklORF9BRERfVFVSSVNUEAQSDwoL",
            "VVBEQVRFX1pCT1IQBRINCglCVVlfQklMRVQQBhIKCgZMT0dPVVQQB2IGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.Angajat), global::Proto.Angajat.Parser, new[]{ "User", "Password" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.Zbor), global::Proto.Zbor.Parser, new[]{ "Destinatia", "DataPlecarii", "Aeroport", "NrLocuri" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.Turist), global::Proto.Turist.Parser, new[]{ "Nume" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.Bilet), global::Proto.Bilet.Parser, new[]{ "Angajat", "Zbor", "Client", "ListaTuristi", "AdresaClient", "NrLocuri" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.Request), global::Proto.Request.Parser, new[]{ "Type", "Zbor", "Name", "Bilet", "Angajat", "Turist" }, new[]{ "Data" }, new[]{ typeof(global::Proto.Request.Types.RequestType) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.Response), global::Proto.Response.Parser, new[]{ "Type", "Error", "Angajat", "Zboruri", "Nume", "Turist", "Zbor" }, null, new[]{ typeof(global::Proto.Response.Types.ResponseType) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Angajat : pb::IMessage<Angajat>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Angajat> _parser = new pb::MessageParser<Angajat>(() => new Angajat());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Angajat> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.CZborReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Angajat() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Angajat(Angajat other) : this() {
      user_ = other.user_;
      password_ = other.password_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Angajat Clone() {
      return new Angajat(this);
    }

    /// <summary>Field number for the "user" field.</summary>
    public const int UserFieldNumber = 1;
    private string user_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string User {
      get { return user_; }
      set {
        user_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "password" field.</summary>
    public const int PasswordFieldNumber = 2;
    private string password_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Password {
      get { return password_; }
      set {
        password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Angajat);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Angajat other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (User != other.User) return false;
      if (Password != other.Password) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (User.Length != 0) hash ^= User.GetHashCode();
      if (Password.Length != 0) hash ^= Password.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (User.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(User);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Password);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (User.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(User);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Password);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (User.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(User);
      }
      if (Password.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Angajat other) {
      if (other == null) {
        return;
      }
      if (other.User.Length != 0) {
        User = other.User;
      }
      if (other.Password.Length != 0) {
        Password = other.Password;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            User = input.ReadString();
            break;
          }
          case 18: {
            Password = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            User = input.ReadString();
            break;
          }
          case 18: {
            Password = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Zbor : pb::IMessage<Zbor>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Zbor> _parser = new pb::MessageParser<Zbor>(() => new Zbor());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Zbor> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.CZborReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Zbor() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Zbor(Zbor other) : this() {
      destinatia_ = other.destinatia_;
      dataPlecarii_ = other.dataPlecarii_;
      aeroport_ = other.aeroport_;
      nrLocuri_ = other.nrLocuri_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Zbor Clone() {
      return new Zbor(this);
    }

    /// <summary>Field number for the "destinatia" field.</summary>
    public const int DestinatiaFieldNumber = 1;
    private string destinatia_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Destinatia {
      get { return destinatia_; }
      set {
        destinatia_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "dataPlecarii" field.</summary>
    public const int DataPlecariiFieldNumber = 2;
    private string dataPlecarii_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DataPlecarii {
      get { return dataPlecarii_; }
      set {
        dataPlecarii_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "aeroport" field.</summary>
    public const int AeroportFieldNumber = 3;
    private string aeroport_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Aeroport {
      get { return aeroport_; }
      set {
        aeroport_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "nrLocuri" field.</summary>
    public const int NrLocuriFieldNumber = 4;
    private int nrLocuri_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NrLocuri {
      get { return nrLocuri_; }
      set {
        nrLocuri_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Zbor);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Zbor other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Destinatia != other.Destinatia) return false;
      if (DataPlecarii != other.DataPlecarii) return false;
      if (Aeroport != other.Aeroport) return false;
      if (NrLocuri != other.NrLocuri) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Destinatia.Length != 0) hash ^= Destinatia.GetHashCode();
      if (DataPlecarii.Length != 0) hash ^= DataPlecarii.GetHashCode();
      if (Aeroport.Length != 0) hash ^= Aeroport.GetHashCode();
      if (NrLocuri != 0) hash ^= NrLocuri.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Destinatia.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Destinatia);
      }
      if (DataPlecarii.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(DataPlecarii);
      }
      if (Aeroport.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Aeroport);
      }
      if (NrLocuri != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(NrLocuri);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Destinatia.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Destinatia);
      }
      if (DataPlecarii.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(DataPlecarii);
      }
      if (Aeroport.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Aeroport);
      }
      if (NrLocuri != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(NrLocuri);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Destinatia.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Destinatia);
      }
      if (DataPlecarii.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DataPlecarii);
      }
      if (Aeroport.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Aeroport);
      }
      if (NrLocuri != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NrLocuri);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Zbor other) {
      if (other == null) {
        return;
      }
      if (other.Destinatia.Length != 0) {
        Destinatia = other.Destinatia;
      }
      if (other.DataPlecarii.Length != 0) {
        DataPlecarii = other.DataPlecarii;
      }
      if (other.Aeroport.Length != 0) {
        Aeroport = other.Aeroport;
      }
      if (other.NrLocuri != 0) {
        NrLocuri = other.NrLocuri;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Destinatia = input.ReadString();
            break;
          }
          case 18: {
            DataPlecarii = input.ReadString();
            break;
          }
          case 26: {
            Aeroport = input.ReadString();
            break;
          }
          case 32: {
            NrLocuri = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Destinatia = input.ReadString();
            break;
          }
          case 18: {
            DataPlecarii = input.ReadString();
            break;
          }
          case 26: {
            Aeroport = input.ReadString();
            break;
          }
          case 32: {
            NrLocuri = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Turist : pb::IMessage<Turist>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Turist> _parser = new pb::MessageParser<Turist>(() => new Turist());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Turist> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.CZborReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Turist() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Turist(Turist other) : this() {
      nume_ = other.nume_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Turist Clone() {
      return new Turist(this);
    }

    /// <summary>Field number for the "nume" field.</summary>
    public const int NumeFieldNumber = 1;
    private string nume_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Nume {
      get { return nume_; }
      set {
        nume_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Turist);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Turist other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Nume != other.Nume) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Nume.Length != 0) hash ^= Nume.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Nume.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Nume);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Nume.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Nume);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Nume.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Nume);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Turist other) {
      if (other == null) {
        return;
      }
      if (other.Nume.Length != 0) {
        Nume = other.Nume;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Nume = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Nume = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Bilet : pb::IMessage<Bilet>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Bilet> _parser = new pb::MessageParser<Bilet>(() => new Bilet());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Bilet> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.CZborReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Bilet() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Bilet(Bilet other) : this() {
      angajat_ = other.angajat_ != null ? other.angajat_.Clone() : null;
      zbor_ = other.zbor_ != null ? other.zbor_.Clone() : null;
      client_ = other.client_ != null ? other.client_.Clone() : null;
      listaTuristi_ = other.listaTuristi_.Clone();
      adresaClient_ = other.adresaClient_;
      nrLocuri_ = other.nrLocuri_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Bilet Clone() {
      return new Bilet(this);
    }

    /// <summary>Field number for the "angajat" field.</summary>
    public const int AngajatFieldNumber = 1;
    private global::Proto.Angajat angajat_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Proto.Angajat Angajat {
      get { return angajat_; }
      set {
        angajat_ = value;
      }
    }

    /// <summary>Field number for the "zbor" field.</summary>
    public const int ZborFieldNumber = 2;
    private global::Proto.Zbor zbor_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Proto.Zbor Zbor {
      get { return zbor_; }
      set {
        zbor_ = value;
      }
    }

    /// <summary>Field number for the "client" field.</summary>
    public const int ClientFieldNumber = 3;
    private global::Proto.Turist client_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Proto.Turist Client {
      get { return client_; }
      set {
        client_ = value;
      }
    }

    /// <summary>Field number for the "listaTuristi" field.</summary>
    public const int ListaTuristiFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Proto.Turist> _repeated_listaTuristi_codec
        = pb::FieldCodec.ForMessage(34, global::Proto.Turist.Parser);
    private readonly pbc::RepeatedField<global::Proto.Turist> listaTuristi_ = new pbc::RepeatedField<global::Proto.Turist>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Proto.Turist> ListaTuristi {
      get { return listaTuristi_; }
    }

    /// <summary>Field number for the "adresaClient" field.</summary>
    public const int AdresaClientFieldNumber = 5;
    private string adresaClient_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AdresaClient {
      get { return adresaClient_; }
      set {
        adresaClient_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "nrLocuri" field.</summary>
    public const int NrLocuriFieldNumber = 6;
    private int nrLocuri_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NrLocuri {
      get { return nrLocuri_; }
      set {
        nrLocuri_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Bilet);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Bilet other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Angajat, other.Angajat)) return false;
      if (!object.Equals(Zbor, other.Zbor)) return false;
      if (!object.Equals(Client, other.Client)) return false;
      if(!listaTuristi_.Equals(other.listaTuristi_)) return false;
      if (AdresaClient != other.AdresaClient) return false;
      if (NrLocuri != other.NrLocuri) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (angajat_ != null) hash ^= Angajat.GetHashCode();
      if (zbor_ != null) hash ^= Zbor.GetHashCode();
      if (client_ != null) hash ^= Client.GetHashCode();
      hash ^= listaTuristi_.GetHashCode();
      if (AdresaClient.Length != 0) hash ^= AdresaClient.GetHashCode();
      if (NrLocuri != 0) hash ^= NrLocuri.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (angajat_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Angajat);
      }
      if (zbor_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Zbor);
      }
      if (client_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Client);
      }
      listaTuristi_.WriteTo(output, _repeated_listaTuristi_codec);
      if (AdresaClient.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(AdresaClient);
      }
      if (NrLocuri != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(NrLocuri);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (angajat_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Angajat);
      }
      if (zbor_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Zbor);
      }
      if (client_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Client);
      }
      listaTuristi_.WriteTo(ref output, _repeated_listaTuristi_codec);
      if (AdresaClient.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(AdresaClient);
      }
      if (NrLocuri != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(NrLocuri);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (angajat_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Angajat);
      }
      if (zbor_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Zbor);
      }
      if (client_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Client);
      }
      size += listaTuristi_.CalculateSize(_repeated_listaTuristi_codec);
      if (AdresaClient.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AdresaClient);
      }
      if (NrLocuri != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NrLocuri);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Bilet other) {
      if (other == null) {
        return;
      }
      if (other.angajat_ != null) {
        if (angajat_ == null) {
          Angajat = new global::Proto.Angajat();
        }
        Angajat.MergeFrom(other.Angajat);
      }
      if (other.zbor_ != null) {
        if (zbor_ == null) {
          Zbor = new global::Proto.Zbor();
        }
        Zbor.MergeFrom(other.Zbor);
      }
      if (other.client_ != null) {
        if (client_ == null) {
          Client = new global::Proto.Turist();
        }
        Client.MergeFrom(other.Client);
      }
      listaTuristi_.Add(other.listaTuristi_);
      if (other.AdresaClient.Length != 0) {
        AdresaClient = other.AdresaClient;
      }
      if (other.NrLocuri != 0) {
        NrLocuri = other.NrLocuri;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (angajat_ == null) {
              Angajat = new global::Proto.Angajat();
            }
            input.ReadMessage(Angajat);
            break;
          }
          case 18: {
            if (zbor_ == null) {
              Zbor = new global::Proto.Zbor();
            }
            input.ReadMessage(Zbor);
            break;
          }
          case 26: {
            if (client_ == null) {
              Client = new global::Proto.Turist();
            }
            input.ReadMessage(Client);
            break;
          }
          case 34: {
            listaTuristi_.AddEntriesFrom(input, _repeated_listaTuristi_codec);
            break;
          }
          case 42: {
            AdresaClient = input.ReadString();
            break;
          }
          case 48: {
            NrLocuri = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (angajat_ == null) {
              Angajat = new global::Proto.Angajat();
            }
            input.ReadMessage(Angajat);
            break;
          }
          case 18: {
            if (zbor_ == null) {
              Zbor = new global::Proto.Zbor();
            }
            input.ReadMessage(Zbor);
            break;
          }
          case 26: {
            if (client_ == null) {
              Client = new global::Proto.Turist();
            }
            input.ReadMessage(Client);
            break;
          }
          case 34: {
            listaTuristi_.AddEntriesFrom(ref input, _repeated_listaTuristi_codec);
            break;
          }
          case 42: {
            AdresaClient = input.ReadString();
            break;
          }
          case 48: {
            NrLocuri = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Request : pb::IMessage<Request>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Request> _parser = new pb::MessageParser<Request>(() => new Request());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Request> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.CZborReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Request() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Request(Request other) : this() {
      type_ = other.type_;
      switch (other.DataCase) {
        case DataOneofCase.Zbor:
          Zbor = other.Zbor.Clone();
          break;
        case DataOneofCase.Name:
          Name = other.Name;
          break;
        case DataOneofCase.Bilet:
          Bilet = other.Bilet.Clone();
          break;
        case DataOneofCase.Angajat:
          Angajat = other.Angajat.Clone();
          break;
        case DataOneofCase.Turist:
          Turist = other.Turist.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Request Clone() {
      return new Request(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Proto.Request.Types.RequestType type_ = global::Proto.Request.Types.RequestType.Login;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Proto.Request.Types.RequestType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "zbor" field.</summary>
    public const int ZborFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Proto.Zbor Zbor {
      get { return dataCase_ == DataOneofCase.Zbor ? (global::Proto.Zbor) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.Zbor;
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return HasName ? (string) data_ : ""; }
      set {
        data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        dataCase_ = DataOneofCase.Name;
      }
    }
    /// <summary>Gets whether the "name" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasName {
      get { return dataCase_ == DataOneofCase.Name; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "name" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearName() {
      if (HasName) {
        ClearData();
      }
    }

    /// <summary>Field number for the "bilet" field.</summary>
    public const int BiletFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Proto.Bilet Bilet {
      get { return dataCase_ == DataOneofCase.Bilet ? (global::Proto.Bilet) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.Bilet;
      }
    }

    /// <summary>Field number for the "angajat" field.</summary>
    public const int AngajatFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Proto.Angajat Angajat {
      get { return dataCase_ == DataOneofCase.Angajat ? (global::Proto.Angajat) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.Angajat;
      }
    }

    /// <summary>Field number for the "turist" field.</summary>
    public const int TuristFieldNumber = 6;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Proto.Turist Turist {
      get { return dataCase_ == DataOneofCase.Turist ? (global::Proto.Turist) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.Turist;
      }
    }

    private object data_;
    /// <summary>Enum of possible cases for the "data" oneof.</summary>
    public enum DataOneofCase {
      None = 0,
      Zbor = 2,
      Name = 3,
      Bilet = 4,
      Angajat = 5,
      Turist = 6,
    }
    private DataOneofCase dataCase_ = DataOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DataOneofCase DataCase {
      get { return dataCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearData() {
      dataCase_ = DataOneofCase.None;
      data_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Request);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Request other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (!object.Equals(Zbor, other.Zbor)) return false;
      if (Name != other.Name) return false;
      if (!object.Equals(Bilet, other.Bilet)) return false;
      if (!object.Equals(Angajat, other.Angajat)) return false;
      if (!object.Equals(Turist, other.Turist)) return false;
      if (DataCase != other.DataCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Proto.Request.Types.RequestType.Login) hash ^= Type.GetHashCode();
      if (dataCase_ == DataOneofCase.Zbor) hash ^= Zbor.GetHashCode();
      if (HasName) hash ^= Name.GetHashCode();
      if (dataCase_ == DataOneofCase.Bilet) hash ^= Bilet.GetHashCode();
      if (dataCase_ == DataOneofCase.Angajat) hash ^= Angajat.GetHashCode();
      if (dataCase_ == DataOneofCase.Turist) hash ^= Turist.GetHashCode();
      hash ^= (int) dataCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::Proto.Request.Types.RequestType.Login) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (dataCase_ == DataOneofCase.Zbor) {
        output.WriteRawTag(18);
        output.WriteMessage(Zbor);
      }
      if (HasName) {
        output.WriteRawTag(26);
        output.WriteString(Name);
      }
      if (dataCase_ == DataOneofCase.Bilet) {
        output.WriteRawTag(34);
        output.WriteMessage(Bilet);
      }
      if (dataCase_ == DataOneofCase.Angajat) {
        output.WriteRawTag(42);
        output.WriteMessage(Angajat);
      }
      if (dataCase_ == DataOneofCase.Turist) {
        output.WriteRawTag(50);
        output.WriteMessage(Turist);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::Proto.Request.Types.RequestType.Login) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (dataCase_ == DataOneofCase.Zbor) {
        output.WriteRawTag(18);
        output.WriteMessage(Zbor);
      }
      if (HasName) {
        output.WriteRawTag(26);
        output.WriteString(Name);
      }
      if (dataCase_ == DataOneofCase.Bilet) {
        output.WriteRawTag(34);
        output.WriteMessage(Bilet);
      }
      if (dataCase_ == DataOneofCase.Angajat) {
        output.WriteRawTag(42);
        output.WriteMessage(Angajat);
      }
      if (dataCase_ == DataOneofCase.Turist) {
        output.WriteRawTag(50);
        output.WriteMessage(Turist);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Proto.Request.Types.RequestType.Login) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (dataCase_ == DataOneofCase.Zbor) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Zbor);
      }
      if (HasName) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (dataCase_ == DataOneofCase.Bilet) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Bilet);
      }
      if (dataCase_ == DataOneofCase.Angajat) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Angajat);
      }
      if (dataCase_ == DataOneofCase.Turist) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Turist);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Request other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Proto.Request.Types.RequestType.Login) {
        Type = other.Type;
      }
      switch (other.DataCase) {
        case DataOneofCase.Zbor:
          if (Zbor == null) {
            Zbor = new global::Proto.Zbor();
          }
          Zbor.MergeFrom(other.Zbor);
          break;
        case DataOneofCase.Name:
          Name = other.Name;
          break;
        case DataOneofCase.Bilet:
          if (Bilet == null) {
            Bilet = new global::Proto.Bilet();
          }
          Bilet.MergeFrom(other.Bilet);
          break;
        case DataOneofCase.Angajat:
          if (Angajat == null) {
            Angajat = new global::Proto.Angajat();
          }
          Angajat.MergeFrom(other.Angajat);
          break;
        case DataOneofCase.Turist:
          if (Turist == null) {
            Turist = new global::Proto.Turist();
          }
          Turist.MergeFrom(other.Turist);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Proto.Request.Types.RequestType) input.ReadEnum();
            break;
          }
          case 18: {
            global::Proto.Zbor subBuilder = new global::Proto.Zbor();
            if (dataCase_ == DataOneofCase.Zbor) {
              subBuilder.MergeFrom(Zbor);
            }
            input.ReadMessage(subBuilder);
            Zbor = subBuilder;
            break;
          }
          case 26: {
            Name = input.ReadString();
            break;
          }
          case 34: {
            global::Proto.Bilet subBuilder = new global::Proto.Bilet();
            if (dataCase_ == DataOneofCase.Bilet) {
              subBuilder.MergeFrom(Bilet);
            }
            input.ReadMessage(subBuilder);
            Bilet = subBuilder;
            break;
          }
          case 42: {
            global::Proto.Angajat subBuilder = new global::Proto.Angajat();
            if (dataCase_ == DataOneofCase.Angajat) {
              subBuilder.MergeFrom(Angajat);
            }
            input.ReadMessage(subBuilder);
            Angajat = subBuilder;
            break;
          }
          case 50: {
            global::Proto.Turist subBuilder = new global::Proto.Turist();
            if (dataCase_ == DataOneofCase.Turist) {
              subBuilder.MergeFrom(Turist);
            }
            input.ReadMessage(subBuilder);
            Turist = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Proto.Request.Types.RequestType) input.ReadEnum();
            break;
          }
          case 18: {
            global::Proto.Zbor subBuilder = new global::Proto.Zbor();
            if (dataCase_ == DataOneofCase.Zbor) {
              subBuilder.MergeFrom(Zbor);
            }
            input.ReadMessage(subBuilder);
            Zbor = subBuilder;
            break;
          }
          case 26: {
            Name = input.ReadString();
            break;
          }
          case 34: {
            global::Proto.Bilet subBuilder = new global::Proto.Bilet();
            if (dataCase_ == DataOneofCase.Bilet) {
              subBuilder.MergeFrom(Bilet);
            }
            input.ReadMessage(subBuilder);
            Bilet = subBuilder;
            break;
          }
          case 42: {
            global::Proto.Angajat subBuilder = new global::Proto.Angajat();
            if (dataCase_ == DataOneofCase.Angajat) {
              subBuilder.MergeFrom(Angajat);
            }
            input.ReadMessage(subBuilder);
            Angajat = subBuilder;
            break;
          }
          case 50: {
            global::Proto.Turist subBuilder = new global::Proto.Turist();
            if (dataCase_ == DataOneofCase.Turist) {
              subBuilder.MergeFrom(Turist);
            }
            input.ReadMessage(subBuilder);
            Turist = subBuilder;
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the Request message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum RequestType {
        [pbr::OriginalName("LOGIN")] Login = 0,
        [pbr::OriginalName("GET_ZBORURI")] GetZboruri = 1,
        [pbr::OriginalName("FILTER_ZBORURI")] FilterZboruri = 2,
        [pbr::OriginalName("BUY_BILET")] BuyBilet = 3,
        [pbr::OriginalName("FIND_ADD_TURIST")] FindAddTurist = 4,
        [pbr::OriginalName("UPDATE_ZBOR")] UpdateZbor = 5,
        [pbr::OriginalName("LOGOUT")] Logout = 6,
      }

    }
    #endregion

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Response : pb::IMessage<Response>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Response> _parser = new pb::MessageParser<Response>(() => new Response());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Response> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.CZborReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Response() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Response(Response other) : this() {
      type_ = other.type_;
      error_ = other.error_;
      angajat_ = other.angajat_ != null ? other.angajat_.Clone() : null;
      zboruri_ = other.zboruri_.Clone();
      nume_ = other.nume_;
      turist_ = other.turist_ != null ? other.turist_.Clone() : null;
      zbor_ = other.zbor_ != null ? other.zbor_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Response Clone() {
      return new Response(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Proto.Response.Types.ResponseType type_ = global::Proto.Response.Types.ResponseType.Ok;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Proto.Response.Types.ResponseType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "error" field.</summary>
    public const int ErrorFieldNumber = 2;
    private string error_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Error {
      get { return error_; }
      set {
        error_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "angajat" field.</summary>
    public const int AngajatFieldNumber = 3;
    private global::Proto.Angajat angajat_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Proto.Angajat Angajat {
      get { return angajat_; }
      set {
        angajat_ = value;
      }
    }

    /// <summary>Field number for the "zboruri" field.</summary>
    public const int ZboruriFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Proto.Zbor> _repeated_zboruri_codec
        = pb::FieldCodec.ForMessage(34, global::Proto.Zbor.Parser);
    private readonly pbc::RepeatedField<global::Proto.Zbor> zboruri_ = new pbc::RepeatedField<global::Proto.Zbor>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Proto.Zbor> Zboruri {
      get { return zboruri_; }
    }

    /// <summary>Field number for the "nume" field.</summary>
    public const int NumeFieldNumber = 5;
    private string nume_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Nume {
      get { return nume_; }
      set {
        nume_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "turist" field.</summary>
    public const int TuristFieldNumber = 6;
    private global::Proto.Turist turist_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Proto.Turist Turist {
      get { return turist_; }
      set {
        turist_ = value;
      }
    }

    /// <summary>Field number for the "zbor" field.</summary>
    public const int ZborFieldNumber = 7;
    private global::Proto.Zbor zbor_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Proto.Zbor Zbor {
      get { return zbor_; }
      set {
        zbor_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Response);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Response other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (Error != other.Error) return false;
      if (!object.Equals(Angajat, other.Angajat)) return false;
      if(!zboruri_.Equals(other.zboruri_)) return false;
      if (Nume != other.Nume) return false;
      if (!object.Equals(Turist, other.Turist)) return false;
      if (!object.Equals(Zbor, other.Zbor)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Proto.Response.Types.ResponseType.Ok) hash ^= Type.GetHashCode();
      if (Error.Length != 0) hash ^= Error.GetHashCode();
      if (angajat_ != null) hash ^= Angajat.GetHashCode();
      hash ^= zboruri_.GetHashCode();
      if (Nume.Length != 0) hash ^= Nume.GetHashCode();
      if (turist_ != null) hash ^= Turist.GetHashCode();
      if (zbor_ != null) hash ^= Zbor.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::Proto.Response.Types.ResponseType.Ok) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Error.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Error);
      }
      if (angajat_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Angajat);
      }
      zboruri_.WriteTo(output, _repeated_zboruri_codec);
      if (Nume.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Nume);
      }
      if (turist_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Turist);
      }
      if (zbor_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Zbor);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::Proto.Response.Types.ResponseType.Ok) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Error.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Error);
      }
      if (angajat_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Angajat);
      }
      zboruri_.WriteTo(ref output, _repeated_zboruri_codec);
      if (Nume.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Nume);
      }
      if (turist_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Turist);
      }
      if (zbor_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Zbor);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Proto.Response.Types.ResponseType.Ok) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (Error.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Error);
      }
      if (angajat_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Angajat);
      }
      size += zboruri_.CalculateSize(_repeated_zboruri_codec);
      if (Nume.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Nume);
      }
      if (turist_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Turist);
      }
      if (zbor_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Zbor);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Response other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Proto.Response.Types.ResponseType.Ok) {
        Type = other.Type;
      }
      if (other.Error.Length != 0) {
        Error = other.Error;
      }
      if (other.angajat_ != null) {
        if (angajat_ == null) {
          Angajat = new global::Proto.Angajat();
        }
        Angajat.MergeFrom(other.Angajat);
      }
      zboruri_.Add(other.zboruri_);
      if (other.Nume.Length != 0) {
        Nume = other.Nume;
      }
      if (other.turist_ != null) {
        if (turist_ == null) {
          Turist = new global::Proto.Turist();
        }
        Turist.MergeFrom(other.Turist);
      }
      if (other.zbor_ != null) {
        if (zbor_ == null) {
          Zbor = new global::Proto.Zbor();
        }
        Zbor.MergeFrom(other.Zbor);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Proto.Response.Types.ResponseType) input.ReadEnum();
            break;
          }
          case 18: {
            Error = input.ReadString();
            break;
          }
          case 26: {
            if (angajat_ == null) {
              Angajat = new global::Proto.Angajat();
            }
            input.ReadMessage(Angajat);
            break;
          }
          case 34: {
            zboruri_.AddEntriesFrom(input, _repeated_zboruri_codec);
            break;
          }
          case 42: {
            Nume = input.ReadString();
            break;
          }
          case 50: {
            if (turist_ == null) {
              Turist = new global::Proto.Turist();
            }
            input.ReadMessage(Turist);
            break;
          }
          case 58: {
            if (zbor_ == null) {
              Zbor = new global::Proto.Zbor();
            }
            input.ReadMessage(Zbor);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Proto.Response.Types.ResponseType) input.ReadEnum();
            break;
          }
          case 18: {
            Error = input.ReadString();
            break;
          }
          case 26: {
            if (angajat_ == null) {
              Angajat = new global::Proto.Angajat();
            }
            input.ReadMessage(Angajat);
            break;
          }
          case 34: {
            zboruri_.AddEntriesFrom(ref input, _repeated_zboruri_codec);
            break;
          }
          case 42: {
            Nume = input.ReadString();
            break;
          }
          case 50: {
            if (turist_ == null) {
              Turist = new global::Proto.Turist();
            }
            input.ReadMessage(Turist);
            break;
          }
          case 58: {
            if (zbor_ == null) {
              Zbor = new global::Proto.Zbor();
            }
            input.ReadMessage(Zbor);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the Response message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum ResponseType {
        [pbr::OriginalName("OK")] Ok = 0,
        [pbr::OriginalName("ERROR")] Error = 1,
        [pbr::OriginalName("GET_ZBORURI")] GetZboruri = 2,
        [pbr::OriginalName("FILTER_ZBORURI")] FilterZboruri = 3,
        [pbr::OriginalName("FIND_ADD_TURIST")] FindAddTurist = 4,
        [pbr::OriginalName("UPDATE_ZBOR")] UpdateZbor = 5,
        [pbr::OriginalName("BUY_BILET")] BuyBilet = 6,
        [pbr::OriginalName("LOGOUT")] Logout = 7,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
